title: Negaça
default_lang: en
author:
  name: Negaça
  email: negaca@capoeiracambridge.co.uk
taxonomies:
  - category
  - tag
metadata:
  description: 'Grupo Negaça Capoeira is a brazilian martial arts group in Cambridge, Saffron Walden and Stapleford'
  keywords: 'Capoeira, Sports, Martial arts, Event, Festival, Batizado, Contrameste, Mestre, Chitaozinho, Olho De Gato, Cambridge, Saffron Walden, Stapleford, Excercise, Group, Lose weight, Fitness, Class, Dance, Acrobatics, Movement, Expression, UK, Portuguese, Brazil, Brazilian, Music, Fight'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
